### ISSUE TITLE
url formation problem

### ISSUE THREAD

**Issue by draffo-dc** [Wolox/wor-requests#19]
There is a problem when we combine the base url with the path, when URI joins them it deletes the path included in the base url.

Example:
base_url = http://someurl.com/v1/
path = users/some_method

URI.join base_url, path      returns  ----->   http://someurl.com/users/some_method   (deletes the v1)

**Comment by Enanodr** [comment]
Another issue is that the block is beeing ignored. The method that ask if block is given doesnt receive a block

**Comment by hdf1986** [comment]
Did you tried with 'users/some_method' or '/users/some_method' ?

I tried doing this. If this is the case we need to see how to handle it better
```
irb(main):001:0> URI.join("http://google.com.ar/test/", "j")
=> #<URI::HTTP http://google.com.ar/test/j>
irb(main):002:0> URI.join("http://google.com.ar/test/", "/j")
=> #<URI::HTTP http://google.com.ar/j>
```

**Comment by Enanodr** [comment]
The second issue i mention, the one with the block i already fixed it with @mishuagopian .
The first, i tried
```
[10] pry(main)> URI.join("http://localhost:4000/v1", "users/00a9d7ab-1d32-469e-a6fc-d968e4052855")
=> #<URI::HTTP http://localhost:4000/users/00a9d7ab-1d32-469e-a6fc-d968e4052855>
[11] pry(main)> URI.join("http://localhost:4000/v1/", "users/00a9d7ab-1d32-469e-a6fc-d968e4052855")
=> #<URI::HTTP http://localhost:4000/v1/users/00a9d7ab-1d32-469e-a6fc-d968e4052855>
[12] pry(main)> URI.join("http://localhost:4000/v1/", "/users/00a9d7ab-1d32-469e-a6fc-d968e4052855")
=> #<URI::HTTP http://localhost:4000/users/00a9d7ab-1d32-469e-a6fc-d968e4052855>
[13] pry(main)> URI.join("http://localhost:4000/v1", "/users/00a9d7ab-1d32-469e-a6fc-d968e4052855")
=> #<URI::HTTP http://localhost:4000/users/00a9d7ab-1d32-469e-a6fc-d968e4052855>
[14] pry(main)> URI.join("http://localhost:4000/v1/", "users/00a9d7ab-1d32-469e-a6fc-d968e4052855")
=> #<URI::HTTP http://localhost:4000/v1/users/00a9d7ab-1d32-469e-a6fc-d968e4052855>
```

Only the last one worked. The base url must have a "/" and the path shouldnt. We have to validate this and not expect the gem user to be aware of this

**Comment by mishuagopian** [comment]
https://github.com/Wolox/wor-requests/pull/21
